### ISSUE TITLE
An error is reported after using pyinstaller to package and run the operation

### ISSUE THREAD

**Issue by qinghemuyu** [wong2/pick#113] opened 2024-03-04 09:29 UTC
![image](https://github.com/wong2/pick/assets/33792031/c4e1aaa8-69b4-4f41-a801-e288ac72661f)

The command is 'pyinstaller -c -F -p C:\Users\Administrator\PycharmProjects\cfgC\venv\Lib\site-packages -i favicon.ico main.py
'

python v3.11

**Comment by aisk** [comment] 2024-04-01 10:13
I'm not familiar with pyinstaller, but I think it's caused by pyinstaller not recognizing the `windows_curses` library, so it's not found. I think pyinstaller has some way to specify the dependencies explicitly.

**Comment by aisk** [comment] 2024-04-07 14:35
If there is no further questions, I'll close it. Feel free to reopen it if you have more context about this issue.

**Closed by aisk** 2024-04-07 14:35 UTC
